<?php

namespace Database\Seeders;

use App\Models\Place;
use Illuminate\Database\Seeder;

class PlaceSeeder extends Seeder
{
    public function run(): void
    {
        $places = [
            // --- APARTMÁN 1 (Ramzová / Jeseníky) ---
            [
                'apartment_id' => 1,
                'name_en' => 'Ramzová Ski Resort',
                'name_cs' => 'Ski aréna Ramzová',
                'name_de' => 'Skigebiet Ramzová',
                'description_en' => 'Direct access to the slopes right outside the door.',
                'description_cs' => 'Přímý přístup na sjezdovky hned za dveřmi.',
                'description_de' => 'Direkter Zugang zu den Pisten direkt vor der Tür.',
                'distance_text_en' => '🚶 1 minute walk',
                'distance_text_cs' => '🚶 1 minuta chůze',
                'distance_text_de' => '🚶 1 Minute Fußweg',
                'icon' => '⛷️',
                'image' => null,
                'latitude' => 50.1931,
                'longitude' => 17.0652,
                'url' => 'https://www.bonera.cz/',
            ],
            [
                'apartment_id' => 1,
                'name_en' => 'Priessnitz Spa',
                'name_cs' => 'Priessnitzovy léčebné lázně',
                'name_de' => 'Priessnitz-Bad',
                'description_en' => 'Famous healing spa founded by Vincenz Priessnitz.',
                'description_cs' => 'Slavné léčebné lázně založené Vincenzem Priessnitzem.',
                'description_de' => 'Berühmtes Heilbad, gegründet von Vincenz Priessnitz.',
                'distance_text_en' => '🚗 15 minutes drive',
                'distance_text_cs' => '🚗 15 minut autem',
                'distance_text_de' => '🚗 15 Minuten Fahrt',
                'icon' => '🏛️',
                'image' => null,
                'latitude' => 50.2415,
                'longitude' => 17.1892,
                'url' => 'https://www.priessnitz.cz/',
            ],
            [
                'apartment_id' => 1,
                'name_en' => 'Praděd Peak',
                'name_cs' => 'Hora Praděd',
                'name_de' => 'Praděd Gipfel',
                'description_en' => 'The highest mountain of the Hrubý Jeseník mountains.',
                'description_cs' => 'Nejvyšší hora Hrubého Jeseníku.',
                'description_de' => 'Der höchste Berg des Altvatergebirges.',
                'distance_text_en' => '🚶‍♂️ 4 hours hike',
                'distance_text_cs' => '🚶‍♂️ 4 hodiny túra',
                'distance_text_de' => '🚶‍♂️ 4 Stunden Wanderung',
                'icon' => '⛰️',
                'image' => null,
                'latitude' => 50.0833,
                'longitude' => 17.2314,
                'url' => null,
            ],
            [
                'apartment_id' => 1,
                'name_en' => 'Šerák Mountain',
                'name_cs' => 'Hora Šerák',
                'name_de' => 'Berg Šerák',
                'description_en' => 'Popular mountain peak accessible by cable car directly from Ramzová.',
                'description_cs' => 'Oblíbený horský vrchol dostupný lanovkou přímo z Ramzové.',
                'description_de' => 'Beliebter Berggipfel, erreichbar mit der Seilbahn direkt von Ramzová.',
                'distance_text_en' => '🚠 15 mins by cable car',
                'distance_text_cs' => '🚠 15 minut lanovkou',
                'distance_text_de' => '🚠 15 Minuten mit der Seilbahn',
                'icon' => '🚠',
                'image' => null,
                'latitude' => 50.1878,
                'longitude' => 17.1069,
                'url' => 'https://www.bonera.cz/lanovky.php',
            ],
            [
                'apartment_id' => 1,
                'name_en' => 'Na Pomezí Caves',
                'name_cs' => 'Jeskyně Na Pomezí',
                'name_de' => 'Höhlen Na Pomezí',
                'description_en' => 'The largest cave system in the Czech Republic formed in crystalline limestone.',
                'description_cs' => 'Největší jeskynní systém v ČR vzniklý v krystalických vápencích.',
                'description_de' => 'Das größte Höhlensystem in Tschechien aus kristallinem Kalkstein.',
                'distance_text_en' => '🚗 10 minutes drive',
                'distance_text_cs' => '🚗 10 minut autem',
                'distance_text_de' => '🚗 10 Minuten Fahrt',
                'icon' => '🦇',
                'image' => null,
                'latitude' => 50.2458,
                'longitude' => 17.1383,
                'url' => 'https://caves.cz/jeskyne/jeskyne-na-pomezi',
            ],

            // --- APARTMÁN 2 (Laa an der Thaya) ---
            [
                'apartment_id' => 2,
                'name_en' => 'Therme Laa',
                'name_cs' => 'Therme Laa',
                'name_de' => 'Therme Laa',
                'description_en' => 'One of the most beautiful thermal baths in lower Austria.',
                'description_cs' => 'Jedny z nejkrásnějších termálních lázní v Dolním Rakousku.',
                'description_de' => 'Eine der schönsten Thermen in Niederösterreich.',
                'distance_text_en' => '🚶 5 minutes walk',
                'distance_text_cs' => '🚶 5 minut chůze',
                'distance_text_de' => '🚶 5 Minuten Fußweg',
                'icon' => '🛁',
                'image' => null,
                'latitude' => 48.7234,
                'longitude' => 16.4012,
                'url' => 'https://www.therme-laa.at/',
            ],
            [
                'apartment_id' => 2,
                'name_en' => 'Bauer Winery',
                'name_cs' => 'Vinařství Bauer',
                'name_de' => 'Weingut Bauer',
                'description_en' => 'A small family-run winery on the outskirts of town. The best Grüner Veltliner in the area.',
                'description_cs' => 'Malé rodinné vinařství na kraji města. Nejlepší Veltlínské zelené v okolí.',
                'description_de' => 'Ein kleines familiengeführtes Weingut am Stadtrand. Der beste Grüne Veltliner in der Umgebung.',
                'distance_text_en' => '🚶 15 minutes walk',
                'distance_text_cs' => '🚶 15 minut chůze',
                'distance_text_de' => '🚶 15 Minuten Fußweg',
                'icon' => '🍷',
                'image' => null,
                'latitude' => 48.7261,
                'longitude' => 16.3955,
                'url' => null,
            ],
            [
                'apartment_id' => 2,
                'name_en' => 'Vienna Center',
                'name_cs' => 'Centrum Vídně',
                'name_de' => 'Zentrum von Wien',
                'description_en' => 'Historic capital city with magnificent architecture.',
                'description_cs' => 'Historické hlavní město s nádhernou architekturou.',
                'description_de' => 'Historische Hauptstadt mit prächtiger Architektur.',
                'distance_text_en' => '🚗 1 hour drive',
                'distance_text_cs' => '🚗 1 hodina autem',
                'distance_text_de' => '🚗 1 Stunde Fahrt',
                'icon' => '🏙️',
                'image' => null,
                'latitude' => 48.2082,
                'longitude' => 16.3738,
                'url' => null,
            ],
            [
                'apartment_id' => 2,
                'name_en' => 'Falkenstein Castle',
                'name_cs' => 'Hrad Falkenstein',
                'name_de' => 'Burgruine Falkenstein',
                'description_en' => 'Impressive castle ruins with a great view over the Weinviertel vineyards.',
                'description_cs' => 'Působivá zřícenina hradu s úžasným výhledem na vinice regionu Weinviertel.',
                'description_de' => 'Beeindruckende Burgruine mit tollem Blick über die Weinberge des Weinviertels.',
                'distance_text_en' => '🚗 20 minutes drive',
                'distance_text_cs' => '🚗 20 minut autem',
                'distance_text_de' => '🚗 20 Minuten Fahrt',
                'icon' => '🏰',
                'image' => null,
                'latitude' => 48.7180,
                'longitude' => 16.5828,
                'url' => 'https://www.falkenstein.gv.at/',
            ],
            [
                'apartment_id' => 2,
                'name_en' => 'Lednice Castle',
                'name_cs' => 'Zámek Lednice',
                'name_de' => 'Schloss Lednice',
                'description_en' => 'Stunning neo-Gothic castle and UNESCO World Heritage site just across the border.',
                'description_cs' => 'Nádherný novogotický zámek a památka UNESCO ležící kousek za hranicemi.',
                'description_de' => 'Atemberaubendes neugotisches Schloss und UNESCO-Weltkulturerbe kurz hinter der Grenze.',
                'distance_text_en' => '🚗 35 minutes drive',
                'distance_text_cs' => '🚗 35 minut autem',
                'distance_text_de' => '🚗 35 Minuten Fahrt',
                'icon' => '👑',
                'image' => null,
                'latitude' => 48.8025,
                'longitude' => 16.8042,
                'url' => 'https://zamek-lednice.com/',
            ],
        ];

        foreach ($places as $place) {
            Place::create($place);
        }
    }
}