version: 2
registries:
  fluxui-composer:
    type: composer-repository
    url: https://composer.fluxui.dev
    username: ${{secrets.FLUX_USERNAME}}
    password: ${{secrets.FLUX_LICENSE_KEY}}
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    registries:
      - fluxui-composer
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"