name: linter

on:
  pull_request:
    branches: [main, dev]

permissions:
  contents: write

jobs:
  php-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Add Flux Credentials
        run: composer config http-basic.composer.fluxui.dev "${{ secrets.FLUX_USERNAME }}" "${{ secrets.FLUX_LICENSE_KEY }}"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Run Pint
        run: php vendor/bin/pint

      - name: Commit PHP Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: fix PHP code style [skip ci]"
          commit_options: '--no-verify'

  js-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node dependencies
        run: npm ci

      - name: Run NPM Lint
        run: npm run lint

      - name: Commit JS/CSS Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: fix frontend code style [skip ci]"
          commit_options: '--no-verify'
